services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    env_file: .env
    environment:
      NODE_ENV: development
